### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by Leundai** [CS196Illinois/CSForGood-Sp2020#15]
Focus on adapting the mockup made Marvel into the app itself with button components and functionality to gallery etc

Set it up with a nice color scheme that is also consistent and organized well

Figure out how to work with the backend into processing the images taken and send it to google OCR

**Comment by gprakarsh** [comment]
We need to create a post request to our back-end and receive feedback from the Google OCR they have set up!

**Comment by gprakarsh** [comment]
All the above tasks are complete
